id: f278e2ef64ce43a4b7a90d541ecd87bd
initial_creation_type: ocr
source_metadata:
  volumes:
    d328750897df49dcb36e218ba9f8011c:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
